---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdatareporting
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: reportingservice
          image: pdecontainerregistry.azurecr.io/reportingservice:_version_
          ports:
            - containerPort: 9005
---
 kind: Service 
 apiVersion: v1 
 metadata: 
   name: reportingservice-svc
 spec: 
   selector: 
     app: web 
   ports: 
   - protocol: TCP 
     port: 9005
     targetPort: 9005
   type: LoadBalancer
